<?php

/**
 * @author Rufusy Idachi
 * @email idachirufus@gmail.com
 * @create date 07-10-2021 11:15:18 
 * @modify date 07-10-2021 11:15:18 
 * @desc Email to send to a servicing department to allocate a lecturer to a course
 */
 
/**
 * @var string $courseName
 * @var string $courseCode
 * @var string $academicYear
 * @var string $servicingDeptName
 * @var string $requestingDeptName
 * @var string $programme
 */

$this->title = 'New course leader creation';
?>
<tr>
    <td class="email-body" width="100%" cellpadding="0" cellspacing="0"
        style="word-break: break-word; margin: 0; padding: 0; font-family: &quot;Nunito Sans&quot;, Helvetica, Arial, sans-serif; font-size: 16px; width: 100%; -premailer-width: 100%; -premailer-cellpadding: 0; -premailer-cellspacing: 0; background-color: #FFFFFF;"
        bgcolor="#FFFFFF">
        <table class="email-body_inner" align="center" width="570" cellpadding="0" cellspacing="0" role="presentation"
            style="width: 570px; -premailer-width: 570px; -premailer-cellpadding: 0; -premailer-cellspacing: 0; background-color: #FFFFFF; margin: 0 auto; padding: 0;"
            bgcolor="#FFFFFF">
            <!-- Body content -->
            <tr>
                <td class="content-cell"
                    style="word-break: break-word; font-family: &quot;Nunito Sans&quot;, Helvetica, Arial, sans-serif; font-size: 16px; padding: 35px;">
                    <div class="f-fallback">
                        <p style="margin-top: 0; color: #333333; font-size: 22px; font-weight: bold; text-align: left;">
                            Dear HOD <?= $servicingDeptName ?>,
                        </p>

                        <p style="font-size: 16px; line-height: 1.625; color: #51545E; margin: .4em 0 1.1875em;">
                            The department of <?= $requestingDeptName ?> has placed a request to your department to
                            service the course: <?= $courseName ?> (<?= $courseCode ?>) under the programme
                            <?= $programme ?> for the academic year <?= $academicYear ?>. Please log in to the system
                            and attend to the request.
                        </p>

                        <p style="font-size: 16px; line-height: 1.625; color: #51545E; margin: .4em 0 1.1875em;">
                            Please log in to the system and attend to the request
                            <a href="https://lecturers.uonbi.ac.ke"> lectures module </a>
                        </p>

                        <p style="font-size: 16px; line-height: 1.625; color: #51545E; margin: .4em 0 1.1875em;">
                            <strong>P.S.</strong> This is an autogenerated message. Please don't reply to it.
                        </p>
                    </div>
                </td>
            </tr>
        </table>
    </td>
</tr>