<?php
/**
 * @author Rufusy Idachi
 * @email idachirufus@gmail.com
 * @create date 22-11-2021
 * @modify date 22-11-2021
 * @desc Email to send on marks update
 */

/**
 * @var string $recipient
 * @var string $courseName
 * @var string $courseCode
 * @var string $academicYear
 * @var string $deptName
 * @var string $assessmentName
 * @var string $registrationNumber
 * @var string $originalMarks
 * @var string $newMarks
 * @var string $level
 * @var string $remarks
 * @var string $recipientLevel
 * @var string $facName
 */

$this->title = 'Change in marks notification';
?>
<tr>
    <td class="email-body" width="100%" cellpadding="0" cellspacing="0"
        style="word-break: break-word; margin: 0; padding: 0; font-family: &quot;Nunito Sans&quot;, Helvetica, Arial, sans-serif; font-size: 16px; width: 100%; -premailer-width: 100%; -premailer-cellpadding: 0; -premailer-cellspacing: 0; background-color: #FFFFFF;"
        bgcolor="#FFFFFF">
        <table class="email-body_inner" align="center" width="570" cellpadding="0" cellspacing="0" role="presentation"
            style="width: 570px; -premailer-width: 570px; -premailer-cellpadding: 0; -premailer-cellspacing: 0; background-color: #FFFFFF; margin: 0 auto; padding: 0;"
            bgcolor="#FFFFFF">
            <!-- Body content -->
            <tr>
                <td class="content-cell"
                    style="word-break: break-word; font-family: &quot;Nunito Sans&quot;, Helvetica, Arial, sans-serif; font-size: 16px; padding: 35px;">
                    <div class="f-fallback">
                        <p style="margin-top: 0; color: #333333; font-size: 22px; font-weight: bold; text-align: left;">
                            Dear <?= $recipient ?>,
                        </p>

                        <p style="font-size: 16px; line-height: 1.625; color: #51545E; margin: .4em 0 1.1875em;">
                            This is to inform you that <?=$assessmentName;?> marks for the unit
                            <?=$courseName . ' (' . $courseCode .') '?> for student <?=$registrationNumber;?> have been
                            changed from <?=$originalMarks;?> to <?=$newMarks;?> at the <?=$level; ?> level with the
                            following remarks:
                        </p>

                        <p style="font-size: 16px; line-height: 1.625; color: #51545E; margin: .4em 0 1.1875em;">
                            <?=$remarks;?>
                        </p>

                        <?php if($recipientLevel === 'lecturer'):?>
                            <p style="font-size: 16px; line-height: 1.625; color: #51545E; margin: .4em 0 1.1875em;">
                                If you have any questions or need any help, please don't hesitate to reach out to your
                                department head.
                            </p>
                        <?php elseif($recipientLevel === 'hod'):?>
                            <p style="font-size: 16px; line-height: 1.625; color: #51545E; margin: .4em 0 1.1875em;">
                                If you have any questions or need any help, please don't hesitate to reach out to your
                                faculty head.
                            </p>
                        <?php endif;?>

                        <p style="font-size: 16px; line-height: 1.625; color: #51545E; margin: .4em 0 1.1875em;">
                            Regards,
                            <br /> 
                            <?php if($level === 'hod'):?>
                                <?=$deptName;?>
                            <?php elseif($level === 'deanDirector'):?>
                                <?=$facName;?>
                            <?php endif;?>
                        </p>
                        
                        <p style="font-size: 16px; line-height: 1.625; color: #51545E; margin: .4em 0 1.1875em;">
                            <strong>P.S.</strong> This is an autogenerated message. Please don't reply to it.
                        </p>
                    </div>
                </td>
            </tr>
        </table>
    </td>
</tr>